2021 vervangen voor 2022, RL tournament weggehaald
timvandenhof/islan-web pull request #19
Opened 2022-05-08 16:42 UTC by michel-douma

2021 vervangen voor 2022, datum volgende LAN aangepast, RL sectie aangepast omdat er dit keer geen tournament is.

2022-05-08 16:42 UTC, michel-douma commented
Wat te doen met ISL2021, wordt dat ISL2022?

2022-05-09 07:37 UTC, timvandenhof commented
Rocket League kaartje doet het niet helemaal goed meer visueel gezien, die moeten we nog even fixen :-)

2022-05-09 07:38 UTC, timvandenhof requested changes
Rocket League wordt nog niet helemaal goed weergegeven.

2022-05-09 08:06 UTC, michel-douma commented
> Rocket League wordt nog niet helemaal goed weergegeven.

Zal ik vanavond doen. Zie het nu ook :') Tijdens ontwikkelen was scherm kleiner en toen zag het er wel goed uit.

2022-05-11 07:34 UTC, timvandenhof approved these changes

2022-05-11 11:05 UTC, merged